/*
 * Robot service 3.0
 * API сервис управления роботом - пылесосом.
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Robot;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RobotApi
 */
@Ignore
public class RobotApiTest {

    private final RobotApi api = new RobotApi();

    /**
     * Добавить робота
     *
     * Добавить робота в базу
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addRobotTest() throws Exception {
        Robot body = null;
        Robot response = api.addRobot(body);

        // TODO: test validations
    }
    /**
     * Удаляет робота
     *
     * Удаляет робота
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRobotTest() throws Exception {
        Long robotId = null;
        String robotId = null;
        api.deleteRobot(robotId, robotId);

        // TODO: test validations
    }
    /**
     * Найти робота по ID
     *
     * вернуть робота
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRobotByIdTest() throws Exception {
        Long robotId = null;
        Robot response = api.getRobotById(robotId);

        // TODO: test validations
    }
    /**
     * Обновить робота
     *
     * Обновить робота
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateRobotTest() throws Exception {
        Robot body = null;
        Robot response = api.updateRobot(body);

        // TODO: test validations
    }
}
